import React, { useState } from 'react';
import VoiceRecognition from './VoiceRecognition';
import OpenAI from './OpenAI';
import TextToSpeech from './TextToSpeech';

function App() {
  const [input, setInput] = useState('');
  const [response, setResponse] = useState('');

  const handleInput = input => {
    setInput(input);
    OpenAI.getResponse(input).then(response => {
      setResponse(response);
      TextToSpeech.speak(response);
    });
  };

  return (
    <div className="App">
      <VoiceRecognition onResult={handleInput} />
      <p>{response}</p>
    </div>
  );
}

export default App;


/*
giv eme the line by line explanation for App.js

Sure, here's a line by line explanation of the code in the App.js file:

python

import React, { useState } from 'react';

This line imports the React library and the useState hook from the React library. The useState hook is a built-in hook in React that allows you to manage state in your functional components.

python

import VoiceRecognition from './VoiceRecognition';

This line imports the VoiceRecognition component from the VoiceRecognition.js file. The VoiceRecognition component is responsible for handling the voice recognition functionality of the application.

javascript

const App = () => {

This line declares a new functional component called App. The component will be a stateless component, since it only needs to render the UI and does not need to manage state.

scss

  const [response, setResponse] = useState('');

This line uses the useState hook to manage the state of the response variable. The response variable will store the text response generated by GPT-3. The setResponse function will be used to update the value of response in the state.

javascript

  return (
    <div className="container">
      <VoiceRecognition setResponse={setResponse} />
      <div className="response">{response}</div>
    </div>
  );
};

This block returns the JSX that will be rendered by the App component. The div with a class name of container is the root container for the component.

Inside the container, there is a call to the VoiceRecognition component, and it passes the setResponse function as a prop to the VoiceRecognition component. This will allow the VoiceRecognition component to update the value of response in the state when a voice input is recognized.

The second div with a class name of response displays the text response generated by GPT-3. The text of the div is set to the value of the response variable, which is part of the component's state.

So, in summary, the App.js file contains the code for the main component of the application. It uses the VoiceRecognition component to handle the voice recognition functionality and displays the text response generated by GPT-3.
*/